In [11]:
import numpy as np

a = np.array([[1, 2],
              [4, 5]])

b = np.array([[7, 8],
              [10, 11]])

c = a @ b
print(c)
print("______________")
d = a+b
print(d)

[[27 30]
 [78 87]]
______________
[[ 8 10]
 [14 16]]


In [13]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

elementwise = A * B
matrix_product = A @ B

print("Element-wise :\n", elementwise)
print("Matrix (dot) product:\n", matrix_product)

Element-wise :
 [[ 5 12]
 [21 32]]
Matrix (dot) product:
 [[19 22]
 [43 50]]


In [14]:
A = np.array([
    [1,2],
    [3,4]
])

print(A.T)


[[1 3]
 [2 4]]


In [15]:
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
A = np.array([
    [2,1],
    [3,4]
])

print(np.linalg.det(A))

5.000000000000001


In [21]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition")
print(A+B)

print("\nSubtraction")
print(A-B)

print("\nElement-wise Multiplication")
print(A*B)
print("\n dot Multiplication")
print(A @B)

Addition
[[ 6  8]
 [10 12]]

Subtraction
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication
[[ 5 12]
 [21 32]]

 dot Multiplication
[[19 22]
 [43 50]]


In [22]:
tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor)

print("Dimensions:", tensor.ndim)
print("Shape:", tensor.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


In [23]:
A = np.array([
    [4,2],
    [1,3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues")
print(eigenvalues)

print("\nEigenvectors")
print(eigenvectors)

Eigenvalues
[5.+0.j 2.+0.j]

Eigenvectors
[[ 0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j  0.70710678+0.j]]


In [25]:
import numpy as np

A = np.array([
    [2,0],
    [0,3]
])

values, vectors = np.linalg.eig(A)

print(values)
print("_____")
print(vectors)

[2.+0.j 3.+0.j]
_____
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]
