In [3]:
import numpy as np

a = np.array([[1, 2],
              [4, 5]])

b = np.array([[7, 8],
              [10, 11]])

c = a @ b
print(c)
print("______________")
d = a+b
print(d)

[[27 30]
 [78 87]]
______________
[[ 8 10]
 [14 16]]


In [4]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

elementwise = A * B
matrix_product = A @ B

print("Element-wise :\n", elementwise)
print("Matrix (dot) product:\n", matrix_product)

Element-wise :
 [[ 5 12]
 [21 32]]
Matrix (dot) product:
 [[19 22]
 [43 50]]


In [5]:
A = np.array([
    [1,2],
    [3,4]
])

print(A.T)


[[1 3]
 [2 4]]


In [6]:
A = np.array([
    [1,2],
    [3,4]
])

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
I = np.eye(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
A = np.array([
    [2,1],
    [3,4]
])

print(np.linalg.det(A))

5.000000000000001


In [9]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition")
print(A+B)

print("\nSubtraction")
print(A-B)

print("\nElement-wise Multiplication")
print(A*B)
print("\n dot Multiplication")
print(A @B)

Addition
[[ 6  8]
 [10 12]]

Subtraction
[[-4 -4]
 [-4 -4]]

Element-wise Multiplication
[[ 5 12]
 [21 32]]

 dot Multiplication
[[19 22]
 [43 50]]


In [10]:
tensor = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(tensor)

print("Dimensions:", tensor.ndim)
print("Shape:", tensor.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3
Shape: (2, 2, 2)


In [11]:
A = np.array([
    [4,2],
    [1,3]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues")
print(eigenvalues)

print("\nEigenvectors")
print(eigenvectors)

Eigenvalues
[5.+0.j 2.+0.j]

Eigenvectors
[[ 0.89442719+0.j -0.70710678+0.j]
 [ 0.4472136 +0.j  0.70710678+0.j]]


In [12]:
import numpy as np

A = np.array([
    [2,0],
    [0,3]
])

values, vectors = np.linalg.eig(A)

print(values)
print("_____")
print(vectors)

[2.+0.j 3.+0.j]
_____
[[1.+0.j 0.+0.j]
 [0.+0.j 1.+0.j]]


In [13]:
import numpy as np

A = np.array([[2, 0, 0],
              [0, 3, 4],
              [0, 4, 9]], dtype=float)

eigenvalues, P = np.linalg.eig(A)
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)

A_reconstructed = P @ D @ P_inv

print("Eigenvalues (diagonal of D):", eigenvalues)
print("Reconstructed A:\n", A_reconstructed.real)
print("Matches original?", np.allclose(A, A_reconstructed.real))

Eigenvalues (diagonal of D): [11.+0.j  1.+0.j  2.+0.j]
Reconstructed A:
 [[2. 0. 0.]
 [0. 3. 4.]
 [0. 4. 9.]]
Matches original? True


In [14]:
import numpy as np

np.random.seed(8)
n_tosses = 10000
tosses = np.random.choice(["H", "T"], size=n_tosses)

n_heads = np.sum(tosses == "H")
empirical_p_heads = n_heads / n_tosses

print(f"Heads: {n_heads}/{n_tosses}")
print(f"Empirical P(Heads) = {empirical_p_heads:.4f}")
print("Theoretical P(Heads) = 0.5")

Heads: 4957/10000
Empirical P(Heads) = 0.4957
Theoretical P(Heads) = 0.5


In [15]:
import numpy as np

P_disease = 0.01
P_no_disease = 1 - P_disease
P_pos_given_disease = 0.95        # sensitivity
P_neg_given_no_disease = 0.90     # specificity
P_pos_given_no_disease = 1 - P_neg_given_no_disease   # false positive rate

# Bayes' theorem:
# P(disease | positive) = P(positive | disease) * P(disease) / P(positive)
P_positive = (P_pos_given_disease * P_disease) + (P_pos_given_no_disease * P_no_disease)
P_disease_given_positive = (P_pos_given_disease * P_disease) / P_positive

print(f"P(positive test) = {P_positive:.4f}")
print(f"P(disease | positive test) = {P_disease_given_positive:.4f}")

P(positive test) = 0.1085
P(disease | positive test) = 0.0876


In [16]:
import numpy as np

scores = np.array([88, 92, 79, 95, 85, 60, 91, 77, 89, 84])

mean_score = np.mean(scores)
median_score = np.median(scores)

print(f"Mean: {mean_score}")
print(f"Median: {median_score}")

Mean: 84.0
Median: 86.5


In [17]:
import numpy as np

data = np.array([12, 15, 14, 10, 18, 20, 9, 16])

variance = np.var(data)
std_dev = np.std(data)

print(f"Variance: {variance:.4f}")
print(f"Standard deviation: {std_dev:.4f}")
print(f"sqrt(variance) == std_dev? {np.isclose(np.sqrt(variance), std_dev)}")

Variance: 12.6875
Standard deviation: 3.5620
sqrt(variance) == std_dev? True


In [18]:
import numpy as np

sample_data = np.array([23, 19, 27, 21, 25])

pop_var = np.var(sample_data, ddof=0)
sample_var = np.var(sample_data, ddof=1)

print(f"Population variance (ddof=0): {pop_var:.4f}")
print(f"Sample variance (ddof=1):     {sample_var:.4f}")

n = len(sample_data)
manual_sample_var = np.sum((sample_data - sample_data.mean())**2) / (n - 1)
print(f"Manual sample variance (n-1): {manual_sample_var:.4f}")

Population variance (ddof=0): 8.0000
Sample variance (ddof=1):     10.0000
Manual sample variance (n-1): 10.0000


In [19]:
import numpy as np

data = np.array([50, 60, 70, 80, 90, 100, 40, 65])

mean_val = data.mean()
std_val = data.std()

z_scores = (data - mean_val) / std_val

print("Z-scores:", np.round(z_scores, 3))
print(f"New mean: {z_scores.mean():.6f}")
print(f"New std:  {z_scores.std():.6f}")

Z-scores: [-1.032 -0.499  0.033  0.566  1.098  1.631 -1.564 -0.233]
New mean: 0.000000
New std:  1.000000


In [20]:
import numpy as np

x = np.array([2, 4, 6, 8, 10, 12])
y = np.array([1, 3, 5, 6, 9, 15])

x_mean, y_mean = x.mean(), y.mean()
covariance = np.sum((x - x_mean) * (y - y_mean)) / len(x)
std_x = np.std(x)
std_y = np.std(y)

manual_r = covariance / (std_x * std_y)
builtin_r = np.corrcoef(x, y)[0, 1]

print(f"Manual Pearson r: {manual_r:.4f}")
print(f"np.corrcoef r:    {builtin_r:.4f}")
print("Match?", np.isclose(manual_r, builtin_r))

Manual Pearson r: 0.9572
np.corrcoef r:    0.9572
Match? True


In [21]:
import numpy as np

np.random.seed(16)
mu, sigma = 50, 5
samples = np.random.normal(loc=mu, scale=sigma, size=10000)

print(f"Specified mean: {mu}, sample mean: {samples.mean():.3f}")
print(f"Specified std:  {sigma}, sample std:  {samples.std():.3f}")

Specified mean: 50, sample mean: 50.030
Specified std:  5, sample std:  5.026


In [22]:
import numpy as np

def f(x):
    return x ** 3

def numerical_derivative(f, x, h=1e-5):
    return (f(x + h) - f(x - h)) / (2 * h)

def exact_derivative(x):
    return 3 * x ** 2      # d/dx[x^3] = 3x^2

x_points = np.array([-2, -1, 0, 1, 2, 3])
numeric = numerical_derivative(f, x_points)
exact = exact_derivative(x_points)

print("x:", x_points)
print("Numerical derivative:", np.round(numeric, 5))
print("Exact derivative:    ", exact)

x: [-2 -1  0  1  2  3]
Numerical derivative: [12.  3.  0.  3. 12. 27.]
Exact derivative:     [12  3  0  3 12 27]
